site_name: Sample doc 1.3.22

theme:
  name: 'material'

site_url: ""
use_directory_urls: false
plugin: []

# markdown_extensions:
#   - codehilite
#   - pymdownx.superfences
#   - admonition

nav:
  - Overview: index.md
  # - Getting started: configuration.md
  # - Integration scenarios:
  #   - Authenticate: integration/auth.md
  #   - Credentials: integration/credential.md
  #   - Get user detail: integration/user.md
  #   - Handle security information: integration/security.md
  #   - Multi Factor Authentication: integration/mfa.md
  # - Changelog : changelog.md
  # - Previous versions: ../
  - API Reference : apis.html
    
